Adds signup form validation. Missing parent email
story-squad/clash-of-the-pencils-web pull request #145
Opened 2021-10-07 23:09 UTC by jlong5795

# Sign Up Form Validation

----Adds field validation to sign up form.----
- Codename checked against RegEx validation
- Birthday verified to be 13+
- Email checked against RegEx validation
- Confirm password field checks against password for character match

- [ ] this checklist is OPTIONAL and serves to show how to format your PR markdown
- [ ] task to implement the feature
- [ ] another task
- [ ] notes on existing tests or plans to test
- [ ] any known problems and plans to solve them

----Any other thoughts...  Need clarification on how to handle sign up for users under 13----

2021-10-08 00:13 UTC, bramirez96 requested changes
We can discuss these changes further when we meet, or I can send you a link to the old code that has the proper sort of setup. Mostly looks okay though. I think we also mentioned rendering an error message?

2021-10-08 00:13 UTC, bramirez96 commented on src/components/forms/SignupForm/SignupForm.tsx
> +    const diff_ms = Date.now() - new Date(dob).getTime();
The rest of our app uses Luxon's `DateTime` object, to be consistent let's use that here as well

2021-10-08 00:13 UTC, bramirez96 commented on src/components/forms/SignupForm/SignupForm.tsx
> +              return age > 12 || "Parent's email is required!";
I think i mentioned it in one of the cards and there's an example on the original source code i linked you to, but we actually need a parent email field in this case. There should be a second field that conditionally renders based on the age input by the user

2021-10-08 00:20 UTC, jlong5795 commented on src/components/forms/SignupForm/SignupForm.tsx
> +              return age > 12 || "Parent's email is required!";
1. The link in the ticket is no longer valid. A merge updated that file and the link is dead. I haven't had a chance to go through commits to find the old version.
2. I wanted to confirm that. The ticket said that was likely the case, but wanted to confirm before I took the time. I can start on that later tonight.

2021-10-08 00:41 UTC, bramirez96 commented on src/components/forms/SignupForm/SignupForm.tsx
> +              return age > 12 || "Parent's email is required!";
I'll get you a new link, that's my fault. Look for it on slack in a few minutes

2021-10-12 00:41 UTC, jlong5795 commented on src/components/forms/SignupForm/SignupForm.tsx
> +    const diff_ms = Date.now() - new Date(dob).getTime();
Updated to using Luxon

2021-10-12 00:42 UTC, jlong5795 commented on src/components/forms/SignupForm/SignupForm.tsx
> +              return age > 12 || "Parent's email is required!";
Removed and changed to conditionally show parent's email.

2021-10-12 23:27 UTC, bramirez96 approved these changes

2021-10-12 23:28 UTC, merged